# Generated by Django 5.0.3 on 2024-04-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quduglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qudug_nomi', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='korsatgichlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sath_quduq', models.FloatField(verbose_name=0.0)),
                ('tempInC', models.IntegerField(default=20)),
                ('PH', models.FloatField(verbose_name=0.0)),
                ('Sim', models.FloatField(verbose_name=0.0)),
                ('mes_date', models.DateTimeField(verbose_name='olingan vaqti')),
                ('quduq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quduglar')),
            ],
        ),
    ]
