# Generated by Django 4.2.11 on 2024-04-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quduglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qudug_nomi', models.CharField(max_length=200, verbose_name='quduq nomi')),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quduq_images', verbose_name='quduq rasmi')),
            ],
            options={
                'verbose_name': 'Quduq',
                'verbose_name_plural': 'Quduqlar',
            },
        ),
        migrations.CreateModel(
            name='korsatgichlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sath_quduq', models.FloatField(default=20.0)),
                ('tempInC', models.FloatField(default=20.0)),
                ('PH', models.FloatField(default=8.0)),
                ('Sim', models.FloatField(default=0.0)),
                ('mes_date', models.DateTimeField(verbose_name='olingan vaqti')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('quduq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quduglar')),
            ],
            options={
                'verbose_name': "Ko'rsatgich",
                'verbose_name_plural': "Ko'rsatgichlar",
            },
        ),
    ]
